---
title: "SCA_SS23_Gruppe105_HA1"
output: html_document
date: "2023-05-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Teil 1: Datenanalyse

## Übersicht

### Aufgabe 1
```{r, eval=FALSE, echo=FALSE}
transactions = read.csv2("HA1_Markt1/output_transactions_8Players_v0020.csv")

summary(transactions)

```

```{r, eval=FALSE, echo=FALSE}
services = read.csv2("HA1_Markt1/output_services_8Players_v0020.csv")

cat("Summary of table 'Services':", "\n\n")
summary(services)

```

```{r, eval=FALSE, echo=FALSE}
costs = read.csv2("HA1_Markt1/output_cost_8Players_v0020.csv")

cat("Summary of table 'Costs':", "\n\n")
summary(costs)

```

```{r, eval=FALSE, echo=FALSE}
prices = read.csv2("HA1_Markt1/output_prices_8Players_v0020.csv")

cat("Summary of table 'Prices':", "\n\n")
summary(prices)

```
### Aufgabe 2
```{r, eval=FALSE, echo=FALSE}
# Transactions
# Remove 2023 data
transactions = transactions[transactions$Year <= 2022 & transactions$Year >= 2018, ]

# Convert Day, Month, Year to factors (categorical data)
transactions$Day = as.factor(transactions$Day)
transactions$Month = as.factor(transactions$Month)
transactions$Year = as.factor(transactions$Year)

summary(transactions)
```
```{r, eval=FALSE, echo=FALSE}
# Services
# Convert Day, Month, Year to factors (categorical data)
services$Day = as.factor(services$Day)
services$Month = as.factor(services$Month)
services$Year = as.factor(services$Year)

summary(services)
```
```{r, eval=FALSE, echo=FALSE}
# Costs
# Convert Month and Year to factors (categorical data)
costs$Month = as.factor(costs$Month)
costs$Year = as.factor(costs$Year)

summary(costs)
```
Prices data is already using appropriate data types.

### Aufgabe 3
```{r, eval=FALSE, echo=FALSE}
regions = data.frame(unique(transactions$region))
colnames(regions) = c("Name")
regions
```

### Aufgabe 4
```{r, eval=FALSE, echo=FALSE}
# Create unique set of vendors and their services
vendors = data.frame(unique(services[, c("service", "vendor")]))

# Order by service and vendor name
vendors = vendors[order(vendors$service, vendors$vendor),]
vendors
```

### Aufgabe 5
```{r, eval=FALSE, echo=FALSE}
# Select subset of just supermarkets in China and South Korea 

# First, define which regions we want to look at
regions_china_sk = c("Shangh", "Peking", "Skorea")

# select only transactions in China and S. Korea, then choose unique store names
supermarkets_china_sk = data.frame(unique(transactions[transactions$region %in% regions_china_sk, c("storename")]))

# Assign useful column name
colnames(supermarkets_china_sk) = c("storename")

supermarkets_china_sk

```

## Marktübersicht
### Aufgabe 6

### Aufgabe 7

### Aufgabe 8

### Aufgabe 9

## Umsatz, Kosten und Profit
### Aufgabe 10

### Aufgabe 11

### Aufgabe 12

### Aufgabe 13

## Bewertung der Logistikdienstleister
### Aufgabe 14

### Aufgabe 15

### Aufgabe 16

### Aufgabe 17

# Teil 2: Projektbeschreibung




