---
title: "Case Study - Gruppen 105 & 201"
subtitle: "Supply Chain Analytics SS23"
author: "Benjamin Grünwald, Cordelia Mena Hernandez, Daniel Glatter, Vinzenz Tom Andreas Schaak"
date: "2023-06-21"
output: pdf_document
header-includes:
  \usepackage{fvextra}
  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
---

# Datenaufbereitung
```{r setup, include=FALSE}
# Laden von Packages
library(readxl)
library(tidyverse)
library(lubridate)
library(forecast)
library(zoo)
library(scales)
library(glue)
library(ggplot2)
library(Metrics)
library(knitr)
library(prophet)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE, echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
# Daten einlesen
materials <- read_excel("data/MBG_Materialverlauf_20230612.xlsx")

# Datentypen konvertieren
materials$ArtikelNr <- as.factor(materials$ArtikelNr)
materials$`Artikel-Bezeichnung` <- as.factor(materials$`Artikel-Bezeichnung`)
materials$EinAutDatTyp <- as.factor(materials$EinAutDatTyp)
materials$PjNr <- as.factor(materials$PjNr)
materials$PjInfo <- as.factor(materials$PjInfo)
materials$ORGAKzl <- as.factor(materials$ORGAKzl)
materials$EinAusDat <- as.Date(materials$EinAusDat)
materials$BstDat <- as.Date(materials$BstDat)

# Nur relevante Materialien für Gruppe B
materials_group_b <- c("DAS N-TOPcon Bifacial Glas-Glas (2+2mm) Black 415 WP",
                         "Rahmenloser Bildhalter Antireflexglas 29,7 x 42",
                         "Kabelbinder 280x4,5 mm schwarz",
                         "FPKU-EM-F PVC- Rohr grau EN50 L=3m",
                         "FINTECH Alu Steckrohr IESR 40 AL (3m)",
                         "3d-U-Scheiben     8,4   M 8         DIN 9021  A2")
materials_b <- materials %>%  filter(`Artikel-Bezeichnung` %in% materials_group_b)

# Klassifizierung der Transaktionen: Projekt, Handel, Einkauf - nach Keywords
projekt <- c('PV-Realisierung', 'PV: Realisierung', 'PV: Tankstelle', 'PV: ET', 'PV: EDEKA', 'PV: MBG', 'PV: MO', 'PV: SolarSun', 'PV-Anlage: Realisierung', 'PV: 15,39', 'PV: 175x', 'PV: 99,83', 'PV: EFH')
handel <- c('PV-Materialverkauf', 'Groß- und')
einkauf <- c('Einkauf')

materials_b <- materials_b %>%
  mutate(klasse=if_else(grepl(paste(projekt, collapse='|'), PjInfo), "Projekt", if_else(grepl(paste(handel, collapse='|'), PjInfo), "Handel", if_else(grepl(paste(einkauf, collapse='|'), PjInfo), "Einkauf", "Anderes"))))

materials_b
```

# Explorative Datenanalyse
## Plot: Bestand über Zeit
```{r}
materials_b %>% 
  ggplot() +
  geom_line(aes(x=EinAusDat,y=Bestand,group=ArtikelNr, color=ArtikelNr
                ))

```

## Plot: Menge über Zeit
```{r}
materials_b %>% 
  ggplot() +
  geom_line(aes(x=EinAusDat,y=Menge,group=ArtikelNr, color=ArtikelNr
                ))
```

## Häufigkeit Materialien
```{r}
materials_b %>% group_by(`Artikel-Bezeichnung`) %>% count() %>% arrange(desc(n))
```

## Häufigkeit EinAusDatTyp
```{r}
materials_b %>% group_by(EinAutDatTyp) %>% count() %>% arrange(desc(n))
```

## Häufigkeiten EinAusDatTyp über alle Materialien
```{r}
materials %>% group_by(EinAutDatTyp) %>% count() %>% arrange(desc(n))
```

## Häufigkeit Projekte
```{r}
materials_b %>% group_by(PjInfo) %>% count() %>% arrange(desc(n))
```

## Plot: Mengen nach EinAusDatTyp
```{r}
materials_b %>% group_by(`Artikel-Bezeichnung`,EinAutDatTyp, month = lubridate::floor_date(EinAusDat, 'month')) %>%
  summarise(volume=sum(Menge)) %>%
  ggplot(aes(x=month,y=volume,group=EinAutDatTyp, color=EinAutDatTyp
                )) +
    geom_line() +
    facet_wrap(~`Artikel-Bezeichnung`, scales = 'free_y')
```

```{r}
# Einzelne Plots pro Artikel für Mengen nach EinAusDatTyp
library(sjPlot)
plots <- materials_b %>% group_by(`Artikel-Bezeichnung`) %>% nest %>% 
  mutate(plot = map2(
    data, `Artikel-Bezeichnung`, 
    ~ ggplot(data = .x, aes(x=EinAusDat,y=Menge,group=EinAutDatTyp, color=EinAutDatTyp)) +
      ggtitle(glue("{.y}")) +
      geom_line())) 

print(plots$plot)
```
## Plot: Korrigierter Bestand (cumsum)
```{r}
mat_verlauf <- materials_b %>%
  filter(EinAutDatTyp == "geliefertAm" | EinAutDatTyp == "BereitDat" | EinAutDatTyp == "PjPhaseDat") %>%
  group_by(`ArtikelNr`) %>%
  mutate(cum_sum = cumsum(Menge))
  

ggplot(data=mat_verlauf, aes(x=EinAusDat, y=cum_sum, fill=`ArtikelNr`)) +
    facet_wrap(~`Artikel-Bezeichnung`, nrow=3, scales="free_y") +
    geom_line() +
    xlab("Zeit") + 
    ylab("Materialmenge") +
    theme(legend.position = "none") +
    ggtitle("EinAutDatTyp = geliefertAm, BereitDat, PjPhaseDat")
```


```{r}
materials_b <- materials_b %>%  group_by(ArtikelNr) %>%  mutate(Menge_diff = Menge - lag(Menge)) 
materials_b
```

```{r}
materials_b %>% 
  ggplot() +
  geom_line(aes(x=EinAusDat,y=Menge_diff,group=ArtikelNr, color=ArtikelNr
                ))
```
```{r}
materials_b <- materials_b %>% group_by(ArtikelNr) %>% mutate(Baseline = mean(Menge))
```

```{r}
evaluation = data.frame(Model = "Baseline",
                        MFE = numeric(1),
                        MAE = numeric(1),
                        MSE = numeric(1),
                        sMAPE = numeric(1))
# MFE berechnen
evaluation[evaluation$Model == "Baseline",] $MFE = mean(materials_b$Menge - materials_b$Baseline)

evaluation[evaluation$Model == "Baseline",] $MAE = mean(abs(materials_b$Menge - materials_b$Baseline))


evaluation[evaluation$Model == "Baseline",] $MSE = mean((materials_b$Menge - materials_b$Baseline)^2)


evaluation[evaluation$Model == "Baseline",] $sMAPE = smape(materials_b$Menge, materials_b$Baseline)

evaluation

```


```{r}
# Berechnen des Durchschnitts nach Wochen

weekly_Menge <- materials_b %>%
  group_by(ArtikelNr, week = floor_date(EinAusDat, 'week')) %>%
  summarise(Menge_per_week= sum(Menge)) 
```

```{r}
# Plot nach Wochen
weekly_Menge %>% 
  ggplot() +
  geom_line(aes(x=week,y=Menge_per_week, group=ArtikelNr, color=ArtikelNr
                ))
```


```{r}
# Berechnen des Durchschnitts nach Monate 
monthly_mean <- weekly_Menge %>%  group_by(ArtikelNr, month=month(week)) %>%
  mutate(mean_Menge= mean(Menge_per_week))
```

```{r}
monthly_mean %>% 
  ggplot() +
  geom_line(aes(x=month,y=mean_Menge, group=ArtikelNr, color=ArtikelNr
                ))
```




```{r}
picks <- materials_b %>% mutate(picks = if_else(Menge < 0, abs(Menge), 0), lot_size = if_else(Menge >= 0, abs(Menge), 0))

```

```{r}
picks %>% 
  ggplot() +
  geom_line(aes(x=EinAusDat,y=picks, group='Artikel-Bezeichnung', color=ArtikelNr, scale = 'free_y'
                ))
```

```{r}
picks %>% 
  ggplot() +
  geom_line(aes(x=EinAusDat,y=lot_size, group='Artikel-Bezeichnung', color=ArtikelNr, scale = 'free_y'
                ))
```

```{r}
picks %>% filter(ArtikelNr == 29523, ) %>% 
  ggplot() +
  geom_line(aes(x=EinAusDat,y=picks, col= 'red')) +
  geom_line(aes(x=EinAusDat,y=lot_size, col='green'))
```
```{r}
picks %>% filter(ArtikelNr == 29523,lot_size !=0 ) %>% 
  ggplot(aes(x=lot_size)) +
  geom_histogram(binwidth=.1, colour="black", fill="white")+
  geom_vline(aes(xintercept=mean(lot_size, na.rm=T)), color="red", linetype="dashed", size=1)
```
```{r}
picks %>% filter(ArtikelNr == 26535, ) %>% 
  ggplot() +
  geom_line(aes(x=EinAusDat,y=lot_size))
```


```{r}
picks %>% filter(ArtikelNr == 26535,lot_size !=0  ) %>%
  ggplot(aes(x=lot_size)) + 
  geom_histogram(binwidth=1,colour="black", fill="white") +
  geom_vline(aes(xintercept=mean(lot_size, na.rm=T)), color="red", linetype="dashed", size=1)
```
```{r}
picks %>% filter(ArtikelNr == 21866,lot_size !=0  ) %>%
  ggplot(aes(x=lot_size)) + 
  geom_histogram(binwidth=1,colour="black", fill="white") +
  geom_vline(aes(xintercept=mean(lot_size, na.rm=T)), color="red", linetype="dashed", size=1)
```
```{r}
picks %>% filter(ArtikelNr == 2628,lot_size !=0  ) %>%
  ggplot(aes(x=lot_size)) + 
  geom_histogram(binwidth=1,colour="black", fill="white") +
  geom_vline(aes(xintercept=mean(lot_size, na.rm=T)), color="red", linetype="dashed", size=1)
```
```{r}
picks %>% filter(ArtikelNr == 26384,lot_size !=0  ) %>%
  ggplot(aes(x=lot_size)) + 
  geom_histogram(binwidth=1,colour="black", fill="white") +
  geom_vline(aes(xintercept=mean(lot_size, na.rm=T)), color="red", linetype="dashed", size=1)
```
```{r}
picks %>% filter(ArtikelNr == 6201,lot_size !=0  ) %>%
  ggplot(aes(x=lot_size)) + 
  geom_histogram(binwidth=1,colour="black", fill="white") +
  geom_vline(aes(xintercept=mean(lot_size, na.rm=T)), color="red", linetype="dashed", size=1)
```
```{r}
picks %>% filter(lot_size !=0) %>%  group_by(`Artikel-Bezeichnung`) %>% summarise(avg_lot = mean(lot_size))
```
```{r}
# Berechnen des Durchschnitts nach Wochen
weekly_picks <- picks %>%
  group_by(ArtikelNr, week = floor_date(EinAusDat, 'week')) %>%
  summarise(picks_per_week= sum(picks)) 
```

```{r}
weekly_avg_picks <- picks %>%
  group_by(ArtikelNr, week = floor_date(EinAusDat, 'week')) %>%
  summarise(avgpicks_per_week= mean(picks)) 
```


```{r}
weekly_meanpick <- weekly_picks %>%  group_by(ArtikelNr) %>%
  mutate(mean_pick = mean(picks_per_week))
```

```{r}
weekly_picks %>% 
  ggplot() +
  geom_line(aes(x=week ,y=picks_per_week, group= ArtikelNr, col= ArtikelNr))
```
```{r}
weekly_avg_picks %>% 
  ggplot() +
  geom_line(aes(x=week ,y=avgpicks_per_week, group= ArtikelNr, col= ArtikelNr))
```


